ror_review/config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create]
  root :to => redirect('/users/new')
  get '/user/new' , :to => "users#new"

  resources :posts


  get "user/posts", to: "users#user_posts"
  post 'user/post/create', to: "posts#create" # I made this because for some reason 
  # the posts create action didnt have a prefix # I also slipped user in the beginning
  # of the url because ROR looked for that when I clicked the create post button
end

ror_review/app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :taggings
  has_many :tags, through: :taggings
end

ror_review/app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :taggings
  has_many :posts, through: :taggings
end

ror_review/app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :Tag
  belongs_to :post
end

ror_review/app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :password, :presence => { :on => create }
  validates :name, :presence => true
  validates :email, :presence => true
  validates :email, format: { with: /\A[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]+\z/, on: :create } 

  has_many :posts
  has_many :taggings
  has_many :tags, through: :taggings
end

ror_review/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

ror_review/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id]) # check the link that you click on - the id is being sent in the params
  end

  def user_posts
    post.find(params[:id])
  user = User.find(params[:id])
  end

  def create
    @post = Post.create(post_params) # how is this going to get the user id??
  end

  private

  def post_params
    params.require(:post).permit(:name, :content, :user_id)
  end
end

ror_review/app/controllers/tags_controller.rb
class TagsController < ApplicationController
end

ror_review/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

ror_review/app/helpers/application_helper.rb
module ApplicationHelper
end

ror_review/app/helpers/posts_helper.rb
module PostsHelper
end

ror_review/app/helpers/tags_helper.rb
module TagsHelper
end

ror_review/app/helpers/users_helper.rb
module UsersHelper
end

ror_review/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RorReview</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

ror_review/app/views/posts/create.html.erb
<h2>newly created post</h2>

ror_review/app/views/posts/index.html.erb
<h2>a lit of all posts</h2>

<% @posts.each do |post| %>
<ul>
  <li><%= link_to post.name, post_path(post) %></li>

</ul>
<% end %>

ror_review/app/views/posts/show.html.erb
<h2><%= @post.name %></h2>

<p><%= @post.content %></p>

ror_review/app/views/users/create.html.erb
<h2>Welcome: <%= @user.name %></h2>
<p>Checkout <%= link_to "your posts", user_posts_path %></p>
<p>Checkout <%= link_to "all posts", posts_path  %></p>

ror_review/app/views/users/new.html.erb
<h2>The form for a new user goes here</h2>

<%= form_for :user, url: users_path do |f| %>
<label>Name:</label><br /><%= f.text_field :name %><br />
<label>Email:</label><br /><%= f.text_field :email %><br />
<label>Password:</label><br /><%= f.password_field :password %><br />
<label>Password_confirmation:</label><br /><%= f.password_field :password_confirmation %><br />
<%= f.submit "Sign Up!" %>
<% end %>